### PR TITLE
171 isochrone center cannot be set as destination

### PR DESCRIPTION
**Pull request by Merydian**
Added the location type option to both isochrone processing algorithms.

### CODE REVIEW

**Review by koebi — CHANGES_REQUESTED** [review]
The entry in the changelog and translation is missing.

We could also think about adding an explanation of `Location Type` in the documentation - do you think that's necessary?

The other option would be to add a tooltip/help/description - QuickOSM does this, via param.setHelp, Saga processing via param.setDescription? Not sure what the best way for this is though…

**Comment by Merydian** [comment]
To me the term `Location type` is not self explanatory. The documentation does link to the online docs, but i think it wouldn't harm to add another short comment. A comment is probably better than a tooltip i'd say, because everything else is shown as a comment?

**Comment by koebi** [comment]
I agree with this, go ahead how you feel it fits.

**Comment by Merydian** [comment]
I called "Location type": "Ortstyp" in the german translation.

**Pull request merged**
