### PR TITLE
Move the config-yaml to general plugin folder to avoid deletion when plugin is updated.

### PR DESCRIPTION
**Pull request by merydian**

### CODE REVIEW

**Comment by MichaelsJP** [comment]
What happens if we have an update for the config file and there is still an old one in the permanent location?

**Comment by Merydian** [comment]
Currently there will probably be a permission denied error.

**Comment by MichaelsJP** [comment]
> Currently there will probably be a permission denied error. One way to solve this could be adding the plugin version to the config file and checking for it, overwriting the old config file when theres a new version.

Wouldn't that be the opposite of what this issue targets to achieve?

**Comment by Merydian** [comment]
The way the current code in this PR handles it is every time the plugin is reloaded or QGis is started, in the init, there's a check that compares the plugin version with the version of the config file. If there's a difference, the old providers will be copied. 
For the case that new parameters (or such) are introduced, @TheGreatRefrigerator and I concluded that a custom logic to incorporate them has to be included. I.e. we can't care for the new parameters in advance. There are warning comments in the init and the config-yaml. 

Maybe this is too much trouble for this issue?

**Comment by MichaelsJP** [comment]
Hm. It's convenient to keep the config. In my opinion, the only thing we really want to keep are the endpoint settings. 
Everything else seems unimportant. What if we just keep this part across updates. The rest is always reset and force copied.

**Comment by MichaelsJP** [comment]
@Merydian Right now we only keep the providers. Imo, that is fine how it is now. Maybe it's worth keeping an additional logic in case we modify the provider selection somehow. Old config structures shouldn't break new configs.

@Merydian What do you think?

**Comment by Merydian** [comment]
The problem i still see is potential issues with the config-yaml being in the plugin folder. I am not certain on how we can make sure there's nothing wrong with that.

**Comment by MichaelsJP** [comment]
> The problem i still see is potential issues with the config-yaml being in the plugin folder. I am not certain on how we can make sure there's nothing wrong with that.

@koebi or  @TheGreatRefrigerator what do you think?

**Comment by TheGreatRefrigerator** [comment]
Maybe we should look into moving our settings to the QGIS plugin settings:
https://docs.qgis.org/3.28/en/docs/pyqgis_developer_cookbook/settings.html?highlight=storing%20settings

We could just JSON.dumps the config object.

**Comment by koebi** [comment]
Maybe [this blog post](https://hannes.enjoys.it/blog/2023/07/plugins-in-qgis3-ini/) is of relevance here?

**Comment by merydian** [comment]
As @TheGreatRefrigerator suggested this now lives here wit QgsSettings: #249

**Pull request closed without merging**
